# Generated by Django 2.1.7 on 2019-03-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0002_auto_20190308_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='food',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
