# Generated by Django 2.1.7 on 2019-03-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0003_auto_20190308_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author_id',
            new_name='author',
        ),
    ]
